#!/usr/bin/env sh

# docker compose by default will sync non-existing node_modules directory on first run
npm install --no-audit --fund=false

npx prisma generate
npm run database:migrate
npm run database:seed
npm run start:dev
