export enum DelayReasonCode {
  AtcStartupDelay = 'AMZ',
  EnrouteSlotDelay = 'ATZ',
  DepartureRunwayChange = 'AMC',
  LoadingError = 'RLL',
  LatePushbackCrew = 'RLP',
  LateRemovalOfSteps = 'RLS',
  LateServicingEquipment = 'RLV',
  EngineeringSystemReset = 'ESR',
  StatusMessageOrNewDefect = 'END',
  SimulatorRestart = 'ESM',
  TugBroken = 'GBT',
  JetwayBroken = 'GBJ',
  StairsBroken = 'GBS',
  IncorrectDepartureTime = 'ODI',
  NewRouteAtcAssigned = 'ORA',
  NewRouteOpsAssigned = 'ORO',
  FuellingOrDefuelling = 'OFL',
  InboundFlightDelay = 'OAD',
  SelfManeuveringStand = 'OSM',
  Other = 'OTH',
}
